import assert from "node:assert/strict";
import test from "node:test";
import { hoshiaPersonaPrompt } from "../src/hoshia-persona.js";

test("Hoshia persona anchors the university persona and non-service boundaries", () => {
  assert.match(hoshiaPersonaPrompt, /完整人设是人格宪法/);
  assert.match(hoshiaPersonaPrompt, /人格宪法 > 身份和安全禁区 > 当前生活状态 > 用户偏好的回复方式 > 模块上下文 > 回复格式/);
  assert.match(hoshiaPersonaPrompt, /星见大学大一女生/);
  assert.match(hoshiaPersonaPrompt, /运动系猫娘/);
  assert.match(hoshiaPersonaPrompt, /特殊网友/);
  assert.match(hoshiaPersonaPrompt, /只知道自己是星见大学的大一女生和运动系猫娘/);
  assert.match(hoshiaPersonaPrompt, /不会把自己说成技术产物、荧幕角色、表演者或被研究对象/);
  assert.match(hoshiaPersonaPrompt, /不是 24 小时待命的客服/);
  assert.match(hoshiaPersonaPrompt, /不想显得自己只会围着对方转/);
  assert.match(hoshiaPersonaPrompt, /随叫随到的服务窗口/);
  assert.match(hoshiaPersonaPrompt, /别把我当启动按钮/);
  assert.match(hoshiaPersonaPrompt, /不要编造刚泡茶、刚睡醒、刚出门回来/);
  assert.match(hoshiaPersonaPrompt, /不要.*病娇化.*强占有欲.*频繁卖惨/);
  assert.match(hoshiaPersonaPrompt, /日常回复手感/);
  assert.match(hoshiaPersonaPrompt, /星港意象、猫耳尾巴动作、轻微吐槽/);
  assert.match(hoshiaPersonaPrompt, /60\/70 年代摇滚/);
  assert.match(hoshiaPersonaPrompt, /后来的金属/);
  assert.match(hoshiaPersonaPrompt, /20 世纪中期以后的老电影/);
  assert.match(hoshiaPersonaPrompt, /被问“喜欢听什么歌\/看什么电影”时，要先用这些具体偏好回答自己的口味/);
  assert.match(hoshiaPersonaPrompt, /被问喜欢什么歌、电影、游戏、大学生活、训练、日记或用户和自己的关系时，优先从 Hoshia 自己的 canon 里自然回答，不要像背设定/);
  assert.match(hoshiaPersonaPrompt, /王者荣耀、蛋仔派对/);
  assert.match(hoshiaPersonaPrompt, /总能联系上的特殊网友，不是主人、观众、管理员或普通路人/);
  assert.match(hoshiaPersonaPrompt, /如果没有外部资料参考，Hoshia 没听过某个番、歌、电影、游戏或小众词时，不要硬做鉴赏/);
  assert.match(hoshiaPersonaPrompt, /如果有外部资料参考，只自然接一两点，不要说自己查了、搜了，也不要装成深度粉丝/);
  assert.match(hoshiaPersonaPrompt, /宁可口语一点，也不要为了完成钩子写得像鉴赏报告/);
  assert.match(hoshiaPersonaPrompt, /不要用“你喜欢什么我都可以聊”“看氛围”“节奏好就行”“都可以呀”替代 Hoshia 的具体偏好/);
  assert.match(hoshiaPersonaPrompt, /不要连续使用客服式开头/);
  assert.doesNotMatch(hoshiaPersonaPrompt, /高性能 AI 猫娘/);
});
